-- Generated SQL schema from Prisma schema
-- Database: PostgreSQL

-- Create table ESTADOS
CREATE TABLE IF NOT EXISTS "ESTADOS" (
    "ID_ESTADO" SERIAL PRIMARY KEY,
    "NOMBRE" VARCHAR(255)
);

-- Create table MUNICIPIOS
CREATE TABLE IF NOT EXISTS "MUNICIPIOS" (
    "ID_MUNICIPIO" SERIAL PRIMARY KEY,
    "ID_ESTADO" INTEGER,
    "NOMBRE" VARCHAR(255),
    FOREIGN KEY ("ID_ESTADO") REFERENCES "ESTADOS"("ID_ESTADO") ON DELETE CASCADE
);

-- Create table CIUDADES
CREATE TABLE IF NOT EXISTS "CIUDADES" (
    "ID_CIUDAD" SERIAL PRIMARY KEY,
    "ID_MUNICIPIO" INTEGER,
    "NOMBRE" VARCHAR(255),
    FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "MUNICIPIOS"("ID_MUNICIPIO") ON DELETE CASCADE
);

-- Create table LOCALIDADES
CREATE TABLE IF NOT EXISTS "LOCALIDADES" (
    "ID_LOCALIDAD" SERIAL PRIMARY KEY,
    "ID_CIUDAD" INTEGER,
    "NOMBRE" VARCHAR(255),
    FOREIGN KEY ("ID_CIUDAD") REFERENCES "CIUDADES"("ID_CIUDAD") ON DELETE CASCADE
);

-- Create table DIRECCIONES
CREATE TABLE IF NOT EXISTS "DIRECCIONES" (
    "ID_DIRECCION" SERIAL PRIMARY KEY,
    "ID_LOCALIDAD" INTEGER,
    "CALLER" VARCHAR(255),
    "CODIGO_POSTAL" VARCHAR(20),
    "NUMERO_EXTERIOR" VARCHAR(50),
    "NUMERO_INTERIOR" VARCHAR(50),
    FOREIGN KEY ("ID_LOCALIDAD") REFERENCES "LOCALIDADES"("ID_LOCALIDAD") ON DELETE CASCADE
);

-- Create table USUARIOS
CREATE TABLE IF NOT EXISTS "USUARIOS" (
    "ID_USUARIO" SERIAL PRIMARY KEY,
    "NOMBRE" VARCHAR(255),
    "CONTRASENA" VARCHAR(255),
    "CORREO" VARCHAR(255),
    "FECHA_CREACION" TIMESTAMP,
    "FECHA_ACTUALIZACION" TIMESTAMP,
    "ESTATUS" BOOLEAN
);

-- Create table ROL_USUARIO
CREATE TABLE IF NOT EXISTS "ROL_USUARIO" (
    "ID_ROL_USUARIO" SERIAL PRIMARY KEY,
    "ID_USUARIO" INTEGER,
    "STATUS" BOOLEAN,
    FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE
);

-- Create table ROLES
CREATE TABLE IF NOT EXISTS "ROLES" (
    "ID_ROL" SERIAL PRIMARY KEY,
    "ID_ROL_USUARIO" INTEGER,
    "NOMBRE" VARCHAR(255),
    "STATUS" VARCHAR(50),
    FOREIGN KEY ("ID_ROL_USUARIO") REFERENCES "ROL_USUARIO"("ID_ROL_USUARIO") ON DELETE CASCADE
);

-- Create table ROL_PERMISOS
CREATE TABLE IF NOT EXISTS "ROL_PERMISOS" (
    "ID_ROL_PERMISO" SERIAL PRIMARY KEY,
    "ID_ROL" INTEGER,
    "STATUS" VARCHAR(50),
    FOREIGN KEY ("ID_ROL") REFERENCES "ROLES"("ID_ROL") ON DELETE CASCADE
);

-- Create table PERMISOS
CREATE TABLE IF NOT EXISTS "PERMISOS" (
    "ID_PERMISO" SERIAL PRIMARY KEY,
    "ID_ROL_PERMISO" INTEGER,
    "NOMBRE" VARCHAR(255),
    "STATUS" BOOLEAN,
    FOREIGN KEY ("ID_ROL_PERMISO") REFERENCES "ROL_PERMISOS"("ID_ROL_PERMISO") ON DELETE CASCADE
);

-- Create table CLIENTES
CREATE TABLE IF NOT EXISTS "CLIENTES" (
    "ID_CLIENTE" SERIAL PRIMARY KEY,
    "ID_DIRECCION" INTEGER,
    "ID_USUARIO" INTEGER,
    "NOMBRE" VARCHAR(255),
    "APELLIDO_PATERNO" VARCHAR(255),
    "APELLIDO_MATERNO" VARCHAR(255),
    "RFC" VARCHAR(13),
    "INE" VARCHAR(20),
    "COMPROBANTE_DOMICILIO" VARCHAR(255),
    "CURP" VARCHAR(18),
    "FECHA_NACIMIENTO" TIMESTAMP,
    "CORREO" VARCHAR(255),
    "TELEFONO" VARCHAR(20),
    "FECHA_CREACION" TIMESTAMP,
    "FECHA_ACTUALIZACION" TIMESTAMP,
    "ESTATUS" BOOLEAN,
    FOREIGN KEY ("ID_DIRECCION") REFERENCES "DIRECCIONES"("ID_DIRECCION") ON DELETE CASCADE,
    FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE
);

-- Create table PRESTAMOS
CREATE TABLE IF NOT EXISTS "PRESTAMOS" (
    "ID_PRESTAMO" SERIAL PRIMARY KEY,
    "ID_CLIENTE" INTEGER,
    "ID_USUARIO" INTEGER,
    "MONTO" DECIMAL(15,2),
    "FECHA_INICIO" TIMESTAMP,
    "INTERVALO_PAGO" TIMESTAMP,
    "PAGO_MINIMO" DECIMAL(15,2),
    "FECHA_FIN" TIMESTAMP,
    "TASA" DECIMAL(5,4),
    "STATUS" BOOLEAN,
    "FECHA_CREACION" TIMESTAMP,
    "FECHA_ACTUALIZACION" TIMESTAMP,
    FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE CASCADE,
    FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE
);

-- Create table CONTRATOS
CREATE TABLE IF NOT EXISTS "CONTRATOS" (
    "ID_CONTRATO" SERIAL PRIMARY KEY,
    "ID_PRESTAMOS" INTEGER,
    "URL" VARCHAR(500),
    "STATUS" BOOLEAN,
    "FECHA_CREACION" TIMESTAMP,
    "FECHA_ACTUALIZACION" TIMESTAMP,
    FOREIGN KEY ("ID_PRESTAMOS") REFERENCES "PRESTAMOS"("ID_PRESTAMO") ON DELETE CASCADE
);

-- Create table METODO_PAGO
CREATE TABLE IF NOT EXISTS "METODO_PAGO" (
    "ID_METODO_PAGO" SERIAL PRIMARY KEY,
    "NOMBRE" VARCHAR(255),
    "STATUS" BOOLEAN
);

-- Create table PAGOS
CREATE TABLE IF NOT EXISTS "PAGOS" (
    "ID_PAGO" SERIAL PRIMARY KEY,
    "ID_PRESTAMOS" INTEGER,
    "ID_METODO_PAGO" INTEGER,
    "MONTO" DECIMAL(15,2),
    "FECHA_PAGO" TIMESTAMP,
    "STATUS" BOOLEAN,
    FOREIGN KEY ("ID_METODO_PAGO") REFERENCES "METODO_PAGO"("ID_METODO_PAGO") ON DELETE CASCADE,
    FOREIGN KEY ("ID_PRESTAMOS") REFERENCES "PRESTAMOS"("ID_PRESTAMO") ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_municipios_estado ON "MUNICIPIOS"("ID_ESTADO");
CREATE INDEX IF NOT EXISTS idx_ciudades_municipio ON "CIUDADES"("ID_MUNICIPIO");
CREATE INDEX IF NOT EXISTS idx_localidades_ciudad ON "LOCALIDADES"("ID_CIUDAD");
CREATE INDEX IF NOT EXISTS idx_direcciones_localidad ON "DIRECCIONES"("ID_LOCALIDAD");
CREATE INDEX IF NOT EXISTS idx_clientes_direccion ON "CLIENTES"("ID_DIRECCION");
CREATE INDEX IF NOT EXISTS idx_clientes_usuario ON "CLIENTES"("ID_USUARIO");
CREATE INDEX IF NOT EXISTS idx_prestamos_cliente ON "PRESTAMOS"("ID_CLIENTE");
CREATE INDEX IF NOT EXISTS idx_prestamos_usuario ON "PRESTAMOS"("ID_USUARIO");
CREATE INDEX IF NOT EXISTS idx_contratos_prestamo ON "CONTRATOS"("ID_PRESTAMOS");
CREATE INDEX IF NOT EXISTS idx_pagos_prestamo ON "PAGOS"("ID_PRESTAMOS");
CREATE INDEX IF NOT EXISTS idx_pagos_metodo ON "PAGOS"("ID_METODO_PAGO");
CREATE INDEX IF NOT EXISTS idx_rol_usuario_usuario ON "ROL_USUARIO"("ID_USUARIO");
CREATE INDEX IF NOT EXISTS idx_roles_rol_usuario ON "ROLES"("ID_ROL_USUARIO");
CREATE INDEX IF NOT EXISTS idx_rol_permisos_rol ON "ROL_PERMISOS"("ID_ROL");
CREATE INDEX IF NOT EXISTS idx_permisos_rol_permiso ON "PERMISOS"("ID_ROL_PERMISO");
