-- CreateTable
CREATE TABLE "CIUDADES" (
    "ID_CIUDAD" INTEGER NOT NULL,
    "ID_MUNICIPIO" INTEGER,
    "NOMBRE" TEXT,

    CONSTRAINT "CIUDADES_pkey" PRIMARY KEY ("ID_CIUDAD")
);

-- CreateTable
CREATE TABLE "CLIENTES" (
    "ID_CLIENTE" INTEGER NOT NULL,
    "ID_DIRECCION" INTEGER,
    "ID_USUARIO" INTEGER,
    "NOMBRE" TEXT,
    "APELLIDO_PATERNO" TEXT,
    "APELLIDO_MATERNO" TEXT,
    "RFC" TEXT,
    "INE" TEXT,
    "COMPROBANTE_DOMICILIO" TEXT,
    "CURP" TEXT,
    "FECHA_NACIMIENTO" TIMESTAMP(3),
    "ESTATUS" BOOLEAN,

    CONSTRAINT "CLIENTES_pkey" PRIMARY KEY ("ID_CLIENTE")
);

-- CreateTable
CREATE TABLE "CONTRATOS" (
    "ID_CONTRATO" INTEGER NOT NULL,
    "ID_PRESTAMOS" INTEGER,
    "URL" TEXT,
    "STATUS" BOOLEAN,

    CONSTRAINT "CONTRATOS_pkey" PRIMARY KEY ("ID_CONTRATO")
);

-- CreateTable
CREATE TABLE "DIRECCIONES" (
    "ID_DIRECCION" INTEGER NOT NULL,
    "ID_LOCALIDAD" INTEGER,
    "CALLER" TEXT,
    "CODIGO_POSTAL" TEXT,
    "NUMERO_EXTERIOR" TEXT,
    "NUMERO_INTERIOR" TEXT,

    CONSTRAINT "DIRECCIONES_pkey" PRIMARY KEY ("ID_DIRECCION")
);

-- CreateTable
CREATE TABLE "ESTADOS" (
    "ID_ESTADO" INTEGER NOT NULL,
    "NOMBRE" TEXT,

    CONSTRAINT "ESTADOS_pkey" PRIMARY KEY ("ID_ESTADO")
);

-- CreateTable
CREATE TABLE "LOCALIDADES" (
    "ID_LOCALIDAD" INTEGER NOT NULL,
    "ID_CIUDAD" INTEGER,
    "NOMBRE" TEXT,

    CONSTRAINT "LOCALIDADES_pkey" PRIMARY KEY ("ID_LOCALIDAD")
);

-- CreateTable
CREATE TABLE "METODO_PAGO" (
    "ID_METODO_PAGO" INTEGER NOT NULL,
    "NOMBRE" TEXT,
    "STATUS" BOOLEAN,

    CONSTRAINT "METODO_PAGO_pkey" PRIMARY KEY ("ID_METODO_PAGO")
);

-- CreateTable
CREATE TABLE "MUNICIPIOS" (
    "ID_MUNICIPIO" INTEGER NOT NULL,
    "ID_ESTADO" INTEGER,
    "NOMBRE" TEXT,

    CONSTRAINT "MUNICIPIOS_pkey" PRIMARY KEY ("ID_MUNICIPIO")
);

-- CreateTable
CREATE TABLE "PAGOS" (
    "ID_PAGO" INTEGER NOT NULL,
    "ID_PRESTAMOS" INTEGER,
    "ID_METODO_PAGO" INTEGER,
    "MONTO" DOUBLE PRECISION,
    "FECHA_PAGO" TIMESTAMP(3),
    "STATUS" BOOLEAN,

    CONSTRAINT "PAGOS_pkey" PRIMARY KEY ("ID_PAGO")
);

-- CreateTable
CREATE TABLE "PERMISOS" (
    "ID_PERMISO" INTEGER NOT NULL,
    "ID_ROL_PERMISO" INTEGER,
    "NOMBRE" TEXT,
    "STATUS" BOOLEAN,

    CONSTRAINT "PERMISOS_pkey" PRIMARY KEY ("ID_PERMISO")
);

-- CreateTable
CREATE TABLE "PRESTAMOS" (
    "ID_PRESTAMO" INTEGER NOT NULL,
    "ID_CLIENTE" INTEGER,
    "ID_USUARIO" INTEGER,
    "MONTO" DOUBLE PRECISION,
    "FECHA_INICIO" TIMESTAMP(3),
    "INTERVALO_PAGO" TIMESTAMP(3),
    "PAGO_MINIMO" DOUBLE PRECISION,
    "FECHA_FIN" TIMESTAMP(3),
    "TASA" DOUBLE PRECISION,
    "STATUS" BOOLEAN,

    CONSTRAINT "PRESTAMOS_pkey" PRIMARY KEY ("ID_PRESTAMO")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "ID_ROL" INTEGER NOT NULL,
    "ID_ROL_USUARIO" INTEGER,
    "NOMBRE" TEXT,
    "STATUS" TEXT,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ID_ROL")
);

-- CreateTable
CREATE TABLE "ROL_PERMISOS" (
    "ID_ROL_PERMISO" INTEGER NOT NULL,
    "ID_ROL" INTEGER,
    "STATUS" TEXT,

    CONSTRAINT "ROL_PERMISOS_pkey" PRIMARY KEY ("ID_ROL_PERMISO")
);

-- CreateTable
CREATE TABLE "ROL_USUARIO" (
    "ID_ROL_USUARIO" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER,
    "STATUS" BOOLEAN,

    CONSTRAINT "ROL_USUARIO_pkey" PRIMARY KEY ("ID_ROL_USUARIO")
);

-- CreateTable
CREATE TABLE "USUARIOS" (
    "ID_USUARIO" INTEGER NOT NULL,
    "NOMBRE" TEXT,
    "CONTRASENA" TEXT,
    "PASSWORD" TEXT,
    "CORREO" TEXT,
    "FECHA_CREACION" TIMESTAMP(3),
    "FECHA_ACTUALIZACION" TIMESTAMP(3),
    "ESTATUS" BOOLEAN,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- AddForeignKey
ALTER TABLE "CIUDADES" ADD CONSTRAINT "CIUDADES_ID_MUNICIPIO_fkey" FOREIGN KEY ("ID_MUNICIPIO") REFERENCES "MUNICIPIOS"("ID_MUNICIPIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_DIRECCION_fkey" FOREIGN KEY ("ID_DIRECCION") REFERENCES "DIRECCIONES"("ID_DIRECCION") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CONTRATOS" ADD CONSTRAINT "CONTRATOS_ID_PRESTAMOS_fkey" FOREIGN KEY ("ID_PRESTAMOS") REFERENCES "PRESTAMOS"("ID_PRESTAMO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DIRECCIONES" ADD CONSTRAINT "DIRECCIONES_ID_LOCALIDAD_fkey" FOREIGN KEY ("ID_LOCALIDAD") REFERENCES "LOCALIDADES"("ID_LOCALIDAD") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LOCALIDADES" ADD CONSTRAINT "LOCALIDADES_ID_CIUDAD_fkey" FOREIGN KEY ("ID_CIUDAD") REFERENCES "CIUDADES"("ID_CIUDAD") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MUNICIPIOS" ADD CONSTRAINT "MUNICIPIOS_ID_ESTADO_fkey" FOREIGN KEY ("ID_ESTADO") REFERENCES "ESTADOS"("ID_ESTADO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PAGOS" ADD CONSTRAINT "PAGOS_ID_PRESTAMOS_fkey" FOREIGN KEY ("ID_PRESTAMOS") REFERENCES "PRESTAMOS"("ID_PRESTAMO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PAGOS" ADD CONSTRAINT "PAGOS_ID_METODO_PAGO_fkey" FOREIGN KEY ("ID_METODO_PAGO") REFERENCES "METODO_PAGO"("ID_METODO_PAGO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PERMISOS" ADD CONSTRAINT "PERMISOS_ID_ROL_PERMISO_fkey" FOREIGN KEY ("ID_ROL_PERMISO") REFERENCES "ROL_PERMISOS"("ID_ROL_PERMISO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRESTAMOS" ADD CONSTRAINT "PRESTAMOS_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "CLIENTES"("ID_CLIENTE") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PRESTAMOS" ADD CONSTRAINT "PRESTAMOS_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLES" ADD CONSTRAINT "ROLES_ID_ROL_USUARIO_fkey" FOREIGN KEY ("ID_ROL_USUARIO") REFERENCES "ROL_USUARIO"("ID_ROL_USUARIO") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROL_PERMISOS" ADD CONSTRAINT "ROL_PERMISOS_ID_ROL_fkey" FOREIGN KEY ("ID_ROL") REFERENCES "ROLES"("ID_ROL") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROL_USUARIO" ADD CONSTRAINT "ROL_USUARIO_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIOS"("ID_USUARIO") ON DELETE CASCADE ON UPDATE CASCADE;
